'use strict';
const TV_MODE=new URLSearchParams(location.search).get('mode')!=='control';
document.body.classList.add(TV_MODE?'tv-mode':'control-mode');
const $=s=>document.querySelector(s),key='uno-arena-v1',empty=()=>({players:[],groups:Array.from({length:10},()=>Array(4).fill(null)),round:0,liveRound:0,event:null,winners:Array(10).fill(null),semis:[],qualifiers:[[],[]],final:[],champion:null,sound:true});
let state=empty(),selected=null,dragged=null,toastTimer,audioContext;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.groups?.length===10&&saved.players?.length<=40)state={...empty(),...saved,liveRound:saved.liveRound??saved.round};}catch{}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=id=>state.players.find(p=>p.id===id)?.name||'Unknown player';
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('#saveStatus').textContent='Storage unavailable — keep this tab open';}}
function tone(win=false){if(!state.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();(win?[523,659,784,1047]:[440,660]).forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.09;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.065,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.25);});}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function confirmAction(title,description,action){$('#confirmTitle').textContent=title;$('#confirmText').textContent=description;$('#acceptDialog').onclick=()=>{$('#confirm').close();action();};$('#confirm').showModal();}
$('#cancelDialog').onclick=()=>$('#confirm').close();
function celebrate(big=false){tone(true);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<(big?110:36);i++){const b=document.createElement('i');b.className='confetti-bit';b.style.cssText=`left:${Math.random()*100}%;background:${['#ff494b','#ffe34a','#4298ff','#56cf91'][i%4]};--drift:${Math.random()*280-140}px;animation-delay:${Math.random()*.4}s`;$('#confetti').append(b);setTimeout(()=>b.remove(),3200);}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function chip(id,mode,g,s){const chosen=mode==='setup'&&selected===id,win=mode==='round'&&state.winners[g]===id||mode==='semi'&&state.qualifiers[g].includes(id)||mode==='final'&&state.champion===id;return `<button class="player ${chosen?'selected':''} ${win?'winner':''}" ${mode==='setup'?'draggable="true"':''} data-id="${id}" data-mode="${mode}" data-g="${g}" data-s="${s}" aria-pressed="${!!(chosen||win)}" aria-label="${escape(name(id))}${mode==='setup'?', select to move':', select '+(mode==='semi'?'qualifier':'winner')}"><span class="badge">${win?'★':escape(name(id).slice(0,1).toUpperCase())}</span><span class="name">${escape(name(id))}</span>${win?'<span class="qualify">'+(mode==='semi'?'TOP 2':'WINNER')+'</span>':`<span class="grip">${mode==='setup'?'⠿':'+'}</span>`}</button>`;}
function game(ids,i,mode){return `<article class="game" style="animation-delay:${Math.min(i,5)*40}ms"><div class="game-head"><strong>${mode==='semi'?'Semi-final':mode==='final'?'Grand final':'Table'} ${mode==='final'?'':String(i+1).padStart(2,'0')}</strong><small>${mode==='setup'?ids.filter(Boolean).length+' / 4 seated':mode==='semi'?state.qualifiers[i].length+' / 2 through':mode==='round'&&state.winners[i]?'COMPLETE':'PLAY TO WIN'}</small></div><div class="seats">${ids.map((id,s)=>mode==='setup'?`<div class="slot" data-g="${i}" data-s="${s}">${id?chip(id,mode,i,s):`<button class="slot" data-place="${i},${s}" aria-label="Place selected player at table ${i+1}, seat ${s+1}">+ Add player</button>`}</div>`:chip(id,mode,i,s)).join('')}</div>${mode==='semi'?'<div class="game-note">Select the first and second players to go out.</div>':''}</article>`;}
function render(){if(TV_MODE)return;save();$('#playerCount').innerHTML=state.players.length+'<span>/ 40</span>';$('#sound').textContent=state.sound?'Sound on ♪':'Sound off';$('#sound').setAttribute('aria-label',state.sound?'Turn sound off':'Turn sound on');const unlocked=state.final.length?3:state.semis.length?2:state.round>0?1:0;$('#stages').innerHTML=['Build the tables','Opening round','Semi-finals','Grand final'].map((s,i)=>`<button data-round="${i}" class="${state.round===i?'active':''}" ${i>unlocked?'disabled':''}><span class="num">${i+1}</span>${s}</button>`).join('');const assigned=new Set(state.groups.flat().filter(Boolean));
if(state.round===0){$('#view').innerHTML=`<div class="workspace"><aside class="sidebar"><div class="section-label">THE PLAYER LINE-UP</div><h2>Who's playing?</h2><p>Enter all 40 names, one per line. Use initials for students with the same name.</p><textarea id="names" aria-label="Student names, one per line" placeholder="Charlie\nRosie\nNed\n…">${escape(state.players.map(p=>p.name).join('\n'))}</textarea><button class="primary" id="addNames">${state.players.length?'Update':'Add'} players</button><button id="loadDemo" style="width:100%;margin-top:10px">Load demo tournament</button><p class="mini" id="inputFeedback">${state.players.length?state.players.length+' players entered.':'Ready when you are.'}</p><div class="format"><b>Waiting to be seated <span style="color:var(--yellow)">${state.players.length-assigned.size}</span></b><p>Drag a name to a seat, or tap a name then a seat. Tap an occupied seat to swap.</p></div><div class="pool" id="pool" aria-label="Unseated players">${state.players.filter(p=>!assigned.has(p.id)).map(p=>chip(p.id,'setup',-1,-1)).join('')||'<span class="mini">'+(state.players.length?'Everyone has a seat.':'Your player cards will appear here.')+'</span>'}</div><div class="format"><b>The road to the final</b><p>10 opening tables of 4 → 2 semi-finals of 5 → top 2 from each → a final table of 4.</p></div></aside><section><div class="board-head"><div><div class="section-label">MAKE YOUR FIRST MATCH-UPS</div><h2>Find your table.</h2><p>Four seats. Ten tables. Let the rivalries begin.</p></div><div class="actions"><button id="shuffle" ${state.players.length!==40?'disabled':''}>⇄ Shuffle all</button><button id="clear" ${!assigned.size?'disabled':''}>Clear tables</button></div></div><div class="games">${state.groups.map((g,i)=>game(g,i,'setup')).join('')}</div><div class="next-bar"><p><b>${assigned.size} of 40 players seated</b><br>Start once every table has four players.</p><button class="primary" id="start" ${assigned.size!==40?'disabled':''}>Start tournament →</button></div></section></div>`;
$('#loadDemo').onclick=()=>{if(state.players.length)confirmAction('Load the demo tournament?','This replaces the current names, seating and results with 40 fictional players.',loadDemo);else loadDemo();};$('#addNames').onclick=()=>{const names=$('#names').value.split('\n').map(n=>n.trim()).filter(Boolean);if(names.length>40||names.some(n=>n.length>45)){toast(names.length>40?'Please enter no more than 40 names.':'Keep each name under 46 characters.');return;}if(new Set(names.map(n=>n.toLowerCase())).size!==names.length){toast('Add initials so every player name is unique.');return;}const apply=()=>{const sound=state.sound;state=empty();state.sound=sound;state.players=names.map((name,i)=>({id:'p'+i,name}));selected=null;render();tone();toast(names.length+' players added');};if(state.players.length)confirmAction('Update the player list?','This clears seating and all results so the new list can be arranged.',apply);else apply();};$('#shuffle').onclick=()=>{state.groups=Array.from({length:10},(_,i)=>shuffleIds.slice(i*4,i*4+4));selected=null;render();tone();};let shuffleIds=shuffle(state.players.map(p=>p.id));$('#clear').onclick=()=>{state.groups=Array.from({length:10},()=>Array(4).fill(null));selected=null;render();};$('#start').onclick=()=>{state.round=1;state.liveRound=1;broadcastEvent('round','OPENING ROUND');state.winners=Array(10).fill(null);state.semis=[];state.qualifiers=[[],[]];state.final=[];state.champion=null;selected=null;render();tone();window.scrollTo({top:0,behavior:'smooth'});};setupDrag();
}else if(state.round===1){const complete=state.winners.filter(Boolean).length;$('#view').innerHTML=`<div class="board-head"><div><div class="section-label">ROUND 01 · 40 PLAYERS</div><h2>The opening round.</h2><p>Play one game at each table. Tap the first player to go out to record the winner.</p></div><span>${complete} / 10 winners</span></div><div class="games">${state.groups.map((g,i)=>game(g,i,'round')).join('')}</div><div class="next-bar"><p>The 10 winners advance to two semi-finals of five.<br>Tables 1, 3, 5, 7, 9 → Semi-final 1 · Tables 2, 4, 6, 8, 10 → Semi-final 2.</p><button class="primary" id="semis" ${complete!==10?'disabled':''}>${state.semis.length?'View':'Create'} semi-finals →</button></div>`;$('#semis').onclick=()=>{if(!state.semis.length)state.semis=[state.winners.filter((_,i)=>i%2===0),state.winners.filter((_,i)=>i%2===1)];state.round=2;state.liveRound=2;broadcastEvent('round','SEMI-FINALS');render();tone();window.scrollTo({top:0,behavior:'smooth'});};
}else if(state.round===2){$('#view').innerHTML=`<section class="wide-games"><div class="board-head"><div><div class="section-label">ROUND 02 · 10 PLAYERS</div><h2>One step from the final.</h2></div></div><div class="round-info"><b>Two players qualify from each table.</b> Record the first player to go out, then keep playing for second place. Everyone gets the same route to the final — no byes.</div><div class="games">${state.semis.map((g,i)=>game(g,i,'semi')).join('')}</div><div class="next-bar"><p><b>${state.qualifiers.flat().length} of 4 finalists selected</b><br>Tap a selected player again to undo.</p><button class="primary" id="final" ${state.qualifiers.some(g=>g.length!==2)?'disabled':''}>${state.final.length?'View':'Create'} grand final →</button></div></section>`;$('#final').onclick=()=>{if(!state.final.length)state.final=state.qualifiers.flat();state.round=3;state.liveRound=3;broadcastEvent('round','GRAND FINAL');render();tone();window.scrollTo({top:0,behavior:'smooth'});};
}else{$('#view').innerHTML=`<section class="wide-games"><div class="board-head"><div><div class="section-label">THE FINAL FOUR</div><h2>${state.champion?'We have a champion.':'This is the big one.'}</h2><p>One final game. The first player to go out is your tournament champion.</p></div></div>${state.champion?`<div class="champion"><div class="champion-mark">★</div><div class="section-label">UNO ARENA CHAMPION</div><h2>${escape(name(state.champion))}</h2><p>Forty players. Three rounds. One unforgettable win.</p><button id="encore">Celebrate again ♪</button></div>`:''}<div class="final-game">${game(state.final,0,'final')}</div></section>`;if($('#encore'))$('#encore').onclick=()=>{broadcastEvent('champion',state.champion,'TOURNAMENT CHAMPION');save();celebrate(true);};}
document.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>{const r=+b.dataset.round;if(r===0&&state.round!==0){confirmAction('Rebuild the opening tables?','Returning to setup clears all match results. Your player names and seating stay in place.',()=>{state.round=0;state.liveRound=0;state.winners=Array(10).fill(null);state.semis=[];state.qualifiers=[[],[]];state.final=[];state.champion=null;render();});}else{state.round=r;render();}});
document.querySelectorAll('.player').forEach(b=>b.onclick=()=>{const {id,mode}=b.dataset,g=+b.dataset.g,s=+b.dataset.s;if(mode==='setup'){if(selected&&selected!==id&&g>=0){move(selected,g,s);return;}selected=selected===id?null:id;render();if(selected)toast('Now choose a seat, or drag the name card.');return;}const action=()=>{if(mode==='round'){state.winners[g]=state.winners[g]===id?null:id;state.semis=[];state.qualifiers=[[],[]];state.final=[];state.champion=null;state.liveRound=1;}else if(mode==='semi'){const q=state.qualifiers[g];if(q.includes(id))state.qualifiers[g]=q.filter(p=>p!==id);else if(q.length<2)q.push(id);else{toast('Unselect one qualifier before choosing another.');return;}state.final=[];state.champion=null;state.liveRound=2;}else state.champion=state.champion===id?null:id;if(mode==='final')state.liveRound=3;const won=mode==='round'?state.winners[g]===id:mode==='semi'?state.qualifiers[g].includes(id):state.champion===id;if(won)broadcastEvent(mode==='final'?'champion':'winner',id,mode==='semi'?'GRAND FINAL QUALIFIER':mode==='round'?'TABLE '+String(g+1).padStart(2,'0')+' WINNER':'TOURNAMENT CHAMPION');render();if(mode==='final'&&state.champion)celebrate(true);else tone();};if(mode==='round'&&state.semis.length||mode==='semi'&&state.final.length)confirmAction('Change this result?','Later rounds will be cleared because the qualifying players may change.',action);else action();});
if(typeof updateControlStrip==='function')updateControlStrip();
}
function loadDemo(){const names=['Alex','Bailey','Cameron','Dakota','Eden','Frankie','Harper','Indigo','Jamie','Kai','Logan','Morgan','Nico','Oakley','Parker','Quinn','Remy','Sage','Taylor','Winter','Arlo','Blake','Cleo','Dylan','Emery','Felix','Georgia','Hugo','Ivy','Jasper','Keira','Luca','Maisie','Noah','Olive','Poppy','Riley','Sam','Theo','Willow'];const sound=state.sound;state=empty();state.sound=sound;state.players=names.map((name,i)=>({id:'p'+i,name}));const ids=shuffle(state.players.map(p=>p.id));state.groups=Array.from({length:10},(_,i)=>ids.slice(i*4,i*4+4));selected=null;render();tone();toast('40 demo players seated — ready to start.');}
function broadcastEvent(type,value,label=''){state.event={id:Date.now()+'-'+Math.random(),at:Date.now(),type,value,label};}
function move(id,g,s){let source=null;state.groups.forEach((group,gi)=>group.forEach((p,si)=>{if(p===id)source=[gi,si];}));const displaced=g>=0?state.groups[g][s]:null;if(source)state.groups[source[0]][source[1]]=displaced;if(g>=0)state.groups[g][s]=id;selected=null;render();tone();}
function setupDrag(){document.querySelectorAll('[draggable]').forEach(b=>{b.ondragstart=e=>{dragged=b.dataset.id;e.dataTransfer.setData('text/plain',dragged);e.dataTransfer.effectAllowed='move';};b.ondragend=()=>{dragged=null;document.querySelectorAll('.over').forEach(x=>x.classList.remove('over'));};});document.querySelectorAll('.slot[data-g]').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('over');};slot.ondragleave=()=>slot.classList.remove('over');slot.ondrop=e=>{e.preventDefault();const id=dragged||e.dataTransfer.getData('text/plain');if(state.players.some(p=>p.id===id))move(id,+slot.dataset.g,+slot.dataset.s);};});document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{if(!selected){toast('Select a player name first.');return;}const [g,s]=b.dataset.place.split(',').map(Number);move(selected,g,s);});const pool=$('#pool');pool.ondragover=e=>e.preventDefault();pool.ondrop=e=>{e.preventDefault();const id=dragged||e.dataTransfer.getData('text/plain');if(state.players.some(p=>p.id===id))move(id,-1,-1);};pool.onclick=e=>{if(e.target===pool&&selected)move(selected,-1,-1);};}
$('#sound').onclick=()=>{state.sound=!state.sound;render();tone();};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Use your browser’s full-screen option.');}};$('#reset').onclick=()=>confirmAction('Start a new tournament?','This removes all names, seating and results from this device.',()=>{const sound=state.sound;state=empty();state.sound=sound;selected=null;render();});render();
