'use strict';
const roundLabels=['Table line-up','Opening round','Semi-finals','Grand final'];
let tvAudioReady=false,toolsTimer,revealTimer,eventQueue=[],revealing=false,lastEvent=state.event?.id,lastSignature='';
const lengthClass=s=>s.length>28?' very-long':s.length>16?' long':'';
const tvName=id=>id?name(id):'SEAT OPEN';
function currentLiveRound(){const r=state.liveRound??state.round;if(r===3&&!state.final.length)return state.semis.length?2:state.round>0?1:0;if(r===2&&!state.semis.length)return state.round>0?1:0;return r;}
function fitStage(){const scale=Math.min(innerWidth/1600,innerHeight/900);$('#tvStage').style.transform=`translate(-50%, -50%) scale(${scale})`;}
function tvTable(ids,index,round){const q=round===2?state.qualifiers[index]:round===1?[state.winners[index]].filter(Boolean):[];const done=round===2?q.length===2:q.length===1;const colour=['','top-blue','top-green','top-yellow'][index%4];return `<section class="tv-table ${colour} ${done?'resolved':''}" style="--i:${index}"><div class="tv-table-header"><strong>${round===2?'SEMI-FINAL':'TABLE'}</strong><b>${String(index+1).padStart(2,'0')}</b></div><div class="tv-roster">${ids.map((id,i)=>`<div class="tv-player ${!id?'empty-seat':''} ${q.includes(id)?'qualified':done?'out':''}"><span class="seat-no">${String(i+1).padStart(2,'0')}</span><span class="tv-name${lengthClass(tvName(id))}">${escape(tvName(id))}</span>${q.includes(id)?'<span class="qualified-star">★</span>':''}</div>`).join('')}</div><div class="tv-table-footer">${done?(round===2?'FINALISTS CONFIRMED':'WINNER CONFIRMED'):round===2?q.length+' / 2 QUALIFIED':round===1?'FIRST OUT ADVANCES':'TAKE YOUR SEAT'}</div></section>`;}
function renderTV(animate=false){const round=currentLiveRound(),champ=round===3&&state.champion;const count=round===0?state.groups.flat().filter(Boolean).length:round===1?state.winners.filter(Boolean).length:round===2?state.qualifiers.flat().length:state.final.length;const total=[40,10,4,4][round];const labels=['PLAYERS SEATED','WINNERS CONFIRMED','FINALISTS CONFIRMED','FINALISTS'][round];const title=champ?'THE <span>CHAMPION.</span>':round===0?'TAKE YOUR <span>SEAT.</span>':round===1?'OPENING <span>ROUND.</span>':round===2?'THE <span>SEMI-FINALS.</span>':'THE <span>GRAND FINAL.</span>';let content='';
if(round<2)content=`<div class="tv-grid">${state.groups.map((g,i)=>tvTable(g,i,round)).join('')}</div>`;
else if(round===2)content=`<div class="tv-semis">${tvTable(state.semis[0],0,2)}<div class="semi-divider"><span>TOP TWO<br>FROM EACH</span><strong>04</strong><span>GO TO<br>THE FINAL</span></div>${tvTable(state.semis[1],1,2)}</div>`;
else if(champ)content=`<div class="champ-stage"><span class="champ-star">★</span><div class="champ-label">UNO ARENA CHAMPION</div><div class="champ-name${lengthClass(name(champ))}">${escape(name(champ))}</div><div class="champ-rule"></div><div class="champ-caption">40 PLAYERS &nbsp; / &nbsp; 3 ROUNDS &nbsp; / &nbsp; 1 CHAMPION</div><span class="champ-star">★</span></div>`;
else content=`<div class="tv-finalists">${state.final.map((id,i)=>`<section class="finalist" style="--i:${i}"><div class="finalist-top">GRAND FINALIST</div><div class="finalist-number">0${i+1}</div><div class="finalist-name${lengthClass(name(id))}">${escape(name(id))}</div><div class="finalist-bottom">ONE GAME FROM GLORY</div></section>`).join('')}</div>`;
const signature=round+'-'+(champ||'');const entry=animate||signature!==lastSignature;lastSignature=signature;
$('#tvContent').className=entry?'stagger-in':'';$('#tvContent').innerHTML=`<div class="broadcast-header"><div class="broadcast-brand"><span class="uno-type">UNO</span><span class="arena-type">ARENA</span><span class="broadcast-edition">CLASSROOM CHAMPIONSHIP</span></div><div class="broadcast-status"><i class="live-indicator ${round===0?'wait':''}"></i>${champ?'TOURNAMENT COMPLETE':round===0?'THE LINE-UP':'IN PLAY'}</div></div><div class="broadcast-title"><div><div class="round-kicker">${champ?'THE LAST PLAYER STANDING':round===0?'40 PLAYERS · 10 TABLES · ONE CHAMPION':round===1?'ROUND 01 / 40 PLAYERS / 10 TABLES':round===2?'ROUND 02 / 10 PLAYERS / 2 TABLES':'ROUND 03 / 4 PLAYERS / 1 TITLE'}</div><h1 class="round-heading">${title}</h1></div><div class="round-counter">${champ?'<strong>01</strong><small>UNDISPUTED<br>CHAMPION</small>':`<strong>${String(count).padStart(2,'0')}<span> / ${total}</span></strong><small>${labels}</small>`}</div></div>${content}<div class="broadcast-footer">${['OPENING ROUND','SEMI-FINALS','GRAND FINAL'].map((s,i)=>`<div class="route-step ${round===i+1?'current':round>i+1?'complete':''}"><span class="route-no">0${i+1}</span><div><b>${s}</b><small>${['10 TABLES OF FOUR','2 TABLES OF FIVE · TOP TWO ADVANCE','FOUR PLAYERS · ONE CHAMPION'][i]}</small></div><span>${['40 → 10','10 → 4','4 → 1'][i]}</span></div>`).join('')}</div>`;
$('#tvSound').textContent=tvAudioReady?(state.sound?'TV sound on ♪':'TV sound muted'):'Enable TV sound ♪';}
function showTools(){if(!TV_MODE)return;$('#tvTools').classList.add('visible');document.body.classList.remove('cursor-hidden');clearTimeout(toolsTimer);toolsTimer=setTimeout(()=>{if(document.activeElement?.closest('#tvTools'))return;$('#tvTools').classList.remove('visible');document.body.classList.add('cursor-hidden');},3000);}
function enableAudio(){try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();tvAudioReady=true;}catch{}$('#tvSound').textContent=state.sound?'TV sound on ♪':'TV sound muted';}
function fanfare(type){if(!tvAudioReady||!state.sound)return;try{const notes=type==='champion'?[392,523,659,784,659,784,1047]:type==='round'?[196,196,261,392,523]:[523,659,784,1047];notes.forEach((f,i)=>{const t=audioContext.currentTime+i*.12,o=audioContext.createOscillator(),g=audioContext.createGain();o.type=i===notes.length-1?'triangle':'sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.09,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+(i===notes.length-1?.7:.3));o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.8);});}catch{}}
function sparks(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return '';return `<div class="tv-sparks">${Array.from({length:70},(_,i)=>`<i class="tv-spark" style="left:${Math.random()*100}%;background:${['#ffce37','#ef3a4e','#228cff','#24c990'][i%4]};--drift:${Math.random()*240-120}px;animation-delay:${Math.random()*.7}s"></i>`).join('')}</div>`;}
function runReveal(){if(revealing||!eventQueue.length)return;revealing=true;const e=eventQueue.shift(),round=e.type==='round',who=round?e.value:name(e.value);$('#tvReveal').innerHTML=`<div class="reveal-backdrop"></div>${round?`<div class="round-reveal"><small>UNO ARENA</small><strong>${escape(who)}</strong><p>LET’S PLAY.</p></div>`:`<div class="winner-reveal"><div class="reveal-label">${escape(e.label)}</div><div class="reveal-name${lengthClass(who)}">${escape(who)}</div><div class="reveal-caption">${e.type==='champion'?'FORTY PLAYERS. ONE CHAMPION.':'THE NEXT ROUND AWAITS.'}</div></div>${sparks()}`}`;fanfare(e.type);revealTimer=setTimeout(()=>{$('#tvReveal').innerHTML='';revealing=false;runReveal();},e.type==='champion'?4800:round?2400:3000);}
function updateControlStrip(){if(TV_MODE)return;const round=currentLiveRound();$('#controlStrip').innerHTML=`<div><strong>TV display: ${state.champion&&round===3?'Champion':roundLabels[round]}</strong><p>Use <b>Open TV display</b>, move that window to the classroom TV, then choose <b>Full screen</b>. Keep this control desk on your computer. Both windows update together in the same browser.</p></div><div class="actions"><button id="sendRound">Show this round on TV</button><button id="replayIntro">Replay round intro</button></div>`;$('#sendRound').onclick=()=>{state.liveRound=state.round;save();updateControlStrip();toast('TV is showing '+roundLabels[state.round].toLowerCase());};$('#replayIntro').disabled=round===0;$('#replayIntro').onclick=()=>{broadcastEvent('round',roundLabels[round].toUpperCase());save();tone();toast('Round intro sent to the TV');};}
function receiveState(next){if(!next||!Array.isArray(next.groups)||next.groups.length!==10)return;state={...empty(),...next};renderTV();if(state.event&&state.event.id!==lastEvent){lastEvent=state.event.id;if(Date.now()-state.event.at<15000){eventQueue.push(state.event);runReveal();}}}
if(TV_MODE){fitStage();renderTV(true);showTools();window.addEventListener('resize',fitStage);window.addEventListener('pointermove',showTools);window.addEventListener('pointerdown',showTools);window.addEventListener('keydown',showTools);window.addEventListener('storage',e=>{if(e.key===key&&e.newValue){try{receiveState(JSON.parse(e.newValue));}catch{}}});$('#tvFullscreen').onclick=async()=>{enableAudio();try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Use your browser’s full-screen option.');}showTools();};$('#tvSound').onclick=()=>{enableAudio();fanfare('winner');showTools();};document.addEventListener('fullscreenchange',()=>{$('#tvFullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';});}
else{updateControlStrip();$('#openTV').onclick=()=>{const w=window.open('?mode=display','unoArenaTV','popup,width=1280,height=720');if(!w)toast('Allow pop-ups to open the TV display.');};}
